// config.js

export const DEVS_INFO = {
  Sobha:
    "Sobha Realty, established in India in 1995, has made a significant impact in Dubai’s real estate market. Renowned for its luxury residential and commercial developments, Sobha Properties is dedicated to creating meticulously designed apartments and villas that embody sophistication and tranquility.With a focus on upholding the highest quality standards, notable projects like Creek Vistas Reserve, Gardenia Villas, Forest Villas, One Park Avenue, and Hartland Greens Apartments showcase the brand's commitment to elegance and innovative design. Sobha Realty not only enhances living spaces but also fosters vibrant communities that prioritize comfort and well-being.",
  DAMAC:
    "Damac Properties has established itself as a leading luxury real estate developer in the Middle East since 2002. Based in Dubai, the company is known for its exceptional quality and innovative designs across a diverse range of residential, commercial, and mixed-use properties.With a strong presence in the UAE and beyond, Damac is recognized for iconic developments like Akoya Oxygen and DAMAC Hills, which create vibrant communities blending modernity with lifestyle amenities. Committed to customer satisfaction and excellence, Damac Properties sets benchmarks in the luxury sector, making it a top choice for investors and homeowners.", // Replace with the actual company number
  Danube:
    "Danube Properties has evolved from a modest store in Deira into one of the region's most trusted real estate brands. Headquartered in Dubai, the company extends its operations across the UAE, KSA, Oman, Bahrain, Qatar, Kuwait, India, and Africa, establishing a strong international presence.Renowned for delivering exceptional quality and prioritizing client satisfaction, Danube Properties consistently sets new standards in the industry. Projects like the innovative transformable apartments of Starz and the vibrant gated community of Petalz exemplify their commitment to convenience and innovation. Each development is designed to enhance the living experience, making Danube a preferred choice for discerning buyers seeking both comfort and modernity.", // Replace with the actual company email address
  Binghatti:
    "Binghatti Developers, led by CEO and Head of Architecture Mr. Muhammad BinGhatti, has been a transformative force in Dubai’s real estate market since 2008. Renowned for its innovative approach, Binghatti has established a distinguished reputation across the MENA region, offering unparalleled living experiences and solidifying its position as an industry leader. The company’s diverse portfolio encompasses a range of properties, from luxurious apartments and villas to commercial spaces, all characterized by sophisticated design and cutting-edge architecture. Key developments are strategically located in sought-after areas such as JVC, Business Bay, and Downtown Dubai, ensuring accessibility and vibrancy. Binghatti Developers is committed to excellence, consistently delivering projects that elevate the standard of living in Dubai.", // Replace with the actual company address
};
